-- Extra tables for the PHP site. Run AFTER 001_travel_kh.sql. Plain Postgres (no Supabase-specific parts).

-- Loyalty: spend -> discount on hotel/restaurant bookings (5 levels)
alter table users add column if not exists total_spent numeric(12,2) not null default 0;
create table if not exists loyalty_levels (level int primary key, min_spent numeric not null, discount_pct numeric not null);
insert into loyalty_levels values (0,0,0),(1,1000,1),(2,2000,2),(3,3000,3),(4,4000,4),(5,5000,5) on conflict do nothing;

-- Notifications (user_id null = everyone)
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  type text not null default 'info',
  title_en text not null, title_kh text, body_en text, body_kh text,
  link text, starts_at timestamptz, created_at timestamptz default now()
);

-- Sponsors slideshow, curated top places, site settings
create table if not exists sponsors (
  id bigint generated by default as identity primary key,
  title text not null, image_urls text, link_url text,
  starts_on date, ends_on date, is_active smallint not null default 1, sort_order int not null default 0
);
create table if not exists top_places (place_id integer primary key references places(id) on delete cascade, sort_order int not null default 0);
create table if not exists app_settings (key text primary key, value text);
insert into app_settings values ('police_call','117'),('fire_call','118'),('police_telegram',''),('fire_telegram',''),('contact_telegram',''),('contact_email','')
  on conflict do nothing;

-- New festival => notification for everybody
create or replace function on_new_festival() returns trigger language plpgsql as $$
begin
  insert into notifications (type, title_en, title_kh, body_en, link, starts_at)
  values ('festival', 'New festival: ' || new.name_en, new.name_kh, new.when_en, '#festivals', now());
  return new;
end $$;
drop trigger if exists festival_notify on festivals;
create trigger festival_notify after insert on festivals for each row execute function on_new_festival();

-- Guide / transport application approved or rejected => notify that user
create or replace function on_application_status() returns trigger language plpgsql as $$
begin
  if new.status is distinct from old.status and new.user_id is not null then
    insert into notifications (user_id, type, title_en, title_kh, body_en)
    values (new.user_id, 'access',
      case new.status when 'approved' then 'Your application was approved' when 'rejected' then 'Your application was rejected' else 'Application status: ' || new.status end,
      case new.status when 'approved' then 'ពាក្យសុំរបស់អ្នកត្រូវបានអនុម័ត' when 'rejected' then 'ពាក្យសុំរបស់អ្នកត្រូវបានបដិសេធ' else null end,
      new.admin_notes);
  end if;
  return new;
end $$;
drop trigger if exists guide_status on guide_applications;
create trigger guide_status after update on guide_applications for each row execute function on_application_status();
drop trigger if exists transport_status on transport_applications;
create trigger transport_status after update on transport_applications for each row execute function on_application_status();
