-- Run after 004.
-- Login rate limiting
create table if not exists login_attempts (
  id bigint generated by default as identity primary key,
  scope text not null, ident text not null, created_at timestamptz not null default now()
);
create index if not exists login_attempts_idx on login_attempts (scope, ident, created_at);

-- Hotel/restaurant booking completed => its price (after discount) counts toward loyalty spend
create or replace function on_booking_completed() returns trigger language plpgsql as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' and new.user_id is not null then
    update users set total_spent = total_spent + coalesce(new.estimated_price_usd, 0) where id = new.user_id;
  end if;
  return new;
end $$;

-- Hotel/restaurant booking status / payment changes => notify the user
create or replace function on_reservation_events() returns trigger language plpgsql as $$
begin
  if new.user_id is not null then
    if new.status is distinct from old.status then
      insert into notifications (user_id, type, title_en) values (new.user_id, 'access', 'Booking R' || new.id || ' (' || new.item_name || '): ' || new.status);
    end if;
    if new.payment_status is distinct from old.payment_status and new.payment_status = 'paid' then
      insert into notifications (user_id, type, title_en) values (new.user_id, 'access', 'Payment received for booking R' || new.id);
    end if;
  end if;
  return new;
end $$;
drop trigger if exists reservation_events on hotel_restaurant_reservations;
create trigger reservation_events after update on hotel_restaurant_reservations for each row execute function on_reservation_events();
