-- Run after 006. View counters, visitor stats, contact messages.
create table if not exists item_views (
  item_type text not null, item_id integer not null, views bigint not null default 0,
  primary key (item_type, item_id)
);
create table if not exists site_stats (name text primary key, count bigint not null default 0);
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null, contact text not null, message text not null,
  is_read smallint not null default 0, created_at timestamptz not null default now()
);
-- same lock-down as the other tables (the PHP site connects as postgres and is not affected)
alter table item_views enable row level security;
alter table site_stats enable row level security;
alter table contact_messages enable row level security;
